plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common')
    implementation project(':infra')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
}

// ./gradlew :auth:bootRun은 로컬 실행이므로 local 프로필 적용
bootRun {
    systemProperty 'spring.profiles.active', 'local'
}
